print('THE PURPOSE OF THIS SCRIPT IS TO ASSESS PLAYER xGI AND ACTUAL GI, \n
TO ATTAIN AN UNDERSTANDING OF PLAYERS THAT ARE CRITICAL FINISHERS \n
VERSUS PLAYERS THAT DO NOT MAKE MUCH OF THEIR CHANCES')
